// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9ZKvQl4E6P3xM50DxEeZZqlOgw-4Wj7U',
    appId: '1:128827474400:web:40f55dcc5c7f0e07f06b85',
    messagingSenderId: '128827474400',
    projectId: 'pricecatch-15f21',
    authDomain: 'pricecatch-15f21.firebaseapp.com',
    storageBucket: 'pricecatch-15f21.firebasestorage.app',
    measurementId: 'G-PDLYM7XKFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF3_-JbtXV719LAPHfKTHdhs-m8lkR5Qs',
    appId: '1:128827474400:android:6442d696c07dcc84f06b85',
    messagingSenderId: '128827474400',
    projectId: 'pricecatch-15f21',
    storageBucket: 'pricecatch-15f21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJG69dur26rADGUYRTzcTaRv4iu3vkYAU',
    appId: '1:128827474400:ios:5987d52b0d380c43f06b85',
    messagingSenderId: '128827474400',
    projectId: 'pricecatch-15f21',
    storageBucket: 'pricecatch-15f21.firebasestorage.app',
    iosBundleId: 'com.example.priceCatchProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJG69dur26rADGUYRTzcTaRv4iu3vkYAU',
    appId: '1:128827474400:ios:5987d52b0d380c43f06b85',
    messagingSenderId: '128827474400',
    projectId: 'pricecatch-15f21',
    storageBucket: 'pricecatch-15f21.firebasestorage.app',
    iosBundleId: 'com.example.priceCatchProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9ZKvQl4E6P3xM50DxEeZZqlOgw-4Wj7U',
    appId: '1:128827474400:web:4361a81acdabd9bbf06b85',
    messagingSenderId: '128827474400',
    projectId: 'pricecatch-15f21',
    authDomain: 'pricecatch-15f21.firebaseapp.com',
    storageBucket: 'pricecatch-15f21.firebasestorage.app',
    measurementId: 'G-QLFR73ENSS',
  );

}